//! Cross-check: the YAML generated by `codev-core::config::render` must
//! parse without error through the `codev-engine::config::ProjectConfig`
//! reader.
//!
//! If a field's serialization changes in the generator without the reader
//! being adjusted, this test turns red — which is what we want. It
//! guarantees that `codev init --yes` produces a file immediately usable by
//! `codev status` on the fresh project.

use codev_core::config::{UserChoices, from_detected, render};
use codev_core::detect::{Detected, locale::DetectedLocale, mcp::DetectedMcp, stack::Stack};
use codev_engine::config::ProjectConfig;

fn detected_full() -> Detected {
    Detected {
        stack: Some(Stack {
            language: "Rust".into(),
            edition_or_version: Some("2024".into()),
            workspace_crate_count: Some(4),
            dependencies_summary: vec!["serde".into()],
        }),
        project_name: Some("codev".into()),
        license: Some("MIT".into()),
        has_ci: true,
        is_git_repo: true,
        mcps: vec![DetectedMcp {
            name: "claude.ai Atlassian Rovo".into(),
            command: None,
            url: Some("https://mcp.atlassian.com/".into()),
            source: ".mcp.json".into(),
        }],
        locale: Some(DetectedLocale {
            var: "LANG".into(),
            value: "fr_FR.UTF-8".into(),
            language: "fr".into(),
        }),
    }
}

#[test]
fn generated_full_yaml_is_readable_by_project_config() {
    let choices = UserChoices {
        workflows: vec![
            "propose".into(),
            "explore".into(),
            "onboard".into(),
            "apply".into(),
            "sync".into(),
            "archive".into(),
            "update".into(),
        ],
        context_addition: Some("Test roundtrip.".into()),
        jira_tool_confirmed: Some("mcp__claude_ai_Atlassian_Rovo__getJiraIssue".to_string()),
        language: None,
    };
    let g = from_detected(&detected_full(), &choices);
    let yaml = render(&g);

    let parsed: ProjectConfig =
        serde_norway::from_str(&yaml).expect("generated YAML must parse through ProjectConfig");

    let workflows = parsed.workflows.expect("workflows present");
    assert_eq!(workflows.len(), 7);
    assert!(workflows.contains(&"apply".to_string()));

    assert_eq!(parsed.language.as_deref(), Some("fr"));

    assert_eq!(
        parsed.mcp.jira_tool.as_deref(),
        Some("mcp__claude_ai_Atlassian_Rovo__getJiraIssue")
    );

    let context = parsed.context.expect("context present");
    assert!(context.contains("Rust workspace"));
    assert!(context.contains("Test roundtrip"));
}

#[test]
fn generated_minimal_yaml_is_readable() {
    let choices = UserChoices {
        workflows: vec!["propose".into(), "explore".into(), "onboard".into()],
        context_addition: None,
        jira_tool_confirmed: None,
        language: None,
    };
    let g = from_detected(&Detected::empty(), &choices);
    let yaml = render(&g);

    let parsed: ProjectConfig = serde_norway::from_str(&yaml).unwrap();
    assert_eq!(parsed.workflows.unwrap().len(), 3);
    assert!(parsed.context.is_none());
    assert_eq!(parsed.language.as_deref(), Some("en"));
    // No `mcp:` block generated → jira_tool missing (default McpConfig).
    assert!(parsed.mcp.jira_tool.is_none());
}
